parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '8.0.14'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        types:
            event_id: 'CodeChallenge\Infrastructure\Doctrine\Type\EventIdType'
            place_id: 'CodeChallenge\Infrastructure\Doctrine\Type\PlaceIdType'
            point: 'CodeChallenge\Infrastructure\Doctrine\Type\PointType'
            post_id: 'CodeChallenge\Infrastructure\Doctrine\Type\PostIdType'
        mapping_types:
            point: point # this is needed to prevent error on update schema command
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Event:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CodeChallenge/Domain/Model/Event'
                prefix: 'CodeChallenge\Domain\Model\Event'
                alias: Event
            Place:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CodeChallenge/Domain/Model/Place'
                prefix: 'CodeChallenge\Domain\Model\Place'
                alias: Place
            Post:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CodeChallenge/Domain/Model/Post'
                prefix: 'CodeChallenge\Domain\Model\Post'
                alias: Post
