jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            event:
                namespace_prefix: ''
                path: '%kernel.root_dir%/CodeChallenge/Infrastructure/Resources/config/serializer'
