services:
    _defaults:
        autowire: true
        autoconfigure: true

    CodeChallenge\Tests\Behat\:
        resource: '../tests/Behat/*'

    CodeChallenge\Tests\Behat\ApiFeatureContext:
        arguments:
            $baseUri: 'http://localhost:8000'