CodeChallenge\Application\Dto\Event\EventDetailDto:
  properties:
    id:
      exclude: false
    name:
      exclude: false
    posts:
      exclude: true
  relations:
    -
      rel: self
      href:
        route: event_detail
        parameters:
          eventId: expr(object.id)
    -
      rel: posts
      embedded:
        content: expr(object.posts)